version: "3.7"

services:
  db:
    image: postgres:alpine
    volumes:
      - .:/EB/
    environment:
      - POSTGRES_USER=nave
      - POSTGRES_PASSWORD=nave
      - POSTGRES_DB=ebs
    ports:
      - "5432:5432"

volumes:
  postgres_data:
